### ISSUE TITLE
Easybuttons?

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/lab-extensions#14]
Do we want to do easybuttons in Jlab?  What is involved?
REF: https://github.com/nbgallery/nbgallery-extensions/blob/main/jupyter_nbgallery/nbextensions/easy_buttons/

**Comment by jeffyjefflabs** [comment]
I don't have strong feelings either way but I know a fair amount of our users like them.  But probably doesn't need to be a priority until Classic is really dead.

A couple similar extensions for reference:
 * https://github.com/eddienko/jupyterlab-colabinspired-codecellbtn
 * https://github.com/jupyterlab-contrib/jlab-enhanced-cell-toolbar

**Comment by mcrutch** [comment]
OBE included in Lab
