### ISSUE TITLE
Why is .origin called when constructing url?

### ISSUE THREAD

**Issue by marto1** [nbgallery/lab-extensions#50]
Hi,

I'm trying to make the jupyterlab extensions work for sending notebooks from a Jupyter instance to NBGallery. It was refusing to work and I went through a couple of versions after which I arrived at the source of the issue: https://github.com/nbgallery/lab-extensions/blob/a1f07299aa94835da375b1b351235457f58efa09/gallerymenu/src/index.ts#L334

Can someone explain why the URLs are constructed using `.origin` instead of e.g. `.href` ? I have my nbgallery instance located at https://domain.com/nbgallery and the /nbgallery part is obviously cut off? Is this a bug or was there some different intention behind this?

I have the environment variables set like so:
```bash
NBGALLERY_URL=https://domain.com/nbgallery
NBGALLERY_CLIENT_NAME=""
NBGALLERY_ENABLE_AUTODOWNLOAD=0
```

**Comment by marto1** [comment]
Hi @mcrutch ,
Thanks for the quick turnaround! I'm using Version 3.2.3 with jupyterlab-nbgallery version 1.0.5 unfortunately since a further push would require a lot more package upgrades that I can't do right now since they will break a lot of other stuff.

**Comment by mcrutch** [comment]
Try installing jupyterlab-nbgallery==1.0.6a0 and see if that works for you.

**Comment by marto1** [comment]
It works! I also tested with NBGALLERY_URL=https://domain.com/nbgallery/ and then it breaks, just a note. Thank you!

**Comment by mcrutch** [comment]
1.0.6a1 might fix that.  There were a couple spots I was still just doing string building manually rather than URLExt.join

**Comment by mcrutch** [comment]
link notebook is the only thing that isn't gonna work right now.  and I am porting all of these changes to the 3.x line for Lab 4.  Probably not going to patch 2.x because 2.x is lab 3.6+ only, 1.x will work in lab 3.6 and lab 4 should use 3.x of the library

**Comment by mcrutch** [comment]
1.0.6 final release is out.  Link Notebook should now work, and save changes works properly now (the alpha releases were broken on save changes)
